name: The Birdhouse
favicon: null
layout_spectrum: 0.8752854629419744
typography_spectrum: 0.3043098603375256
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1b1a18'
    - '#bf3030'
    - '#5993a4'
    - '#f2e1cd'
    - '#676058'
  brandStrength: 0.75
  lightness: 0.5625
  saturation: 0.5625
  rhythmicContrast: 0.8317720368504524
purpose: []
