typography_spectrum: 0.3043098603375256
color:
  brandColors:
    - '#1b1a18'
    - '#bf3030'
    - '#5993a4'
    - '#f2e1cd'
    - '#676058'
  brandStrength: 0.75
  lightness: 0.5625
  saturation: 0.5625
  rhythmicContrast: 0.8317720368504524
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.8752854629419744
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Scott Golas
  email: scott@spokeandbird.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/66d6573d-fecf-4ae0-9c7d-f2f7b2554a0e.svg
name: The Birdhouse
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Sourcing runs deep with this one...
    url: >-
      http://goodfoodoneverytable.org/2016/08/22/nothing-goes-waste-chicagos-spoke-bird/
    type: external
  - name: Ina Pinkney's take on us...
    url: >-
      http://www.chicagotribune.com/dining/restaurants/ct-breakfast-with-ina-may-food-0525-20160519-story.html
    type: external
favicon: null
title: Bringing local from the field to your plate
description: We do more than just talk about doing local
purpose: []
