name: The Birdhouse
favicon: null
layout_spectrum: 0.8752854629419744
typography_spectrum: 0.3043098603375256
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#5f5f5f'
    - '#00ffff'
    - '#9fffff'
    - '#3fffff'
  brandStrength: 0.878538210876286
  lightness: 0.8855104267131537
  saturation: 0.7714748098514974
  rhythmicContrast: 0.8317720368504524
purpose: []
